# Generated by Django 2.1.1 on 2019-10-19 05:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=20)),
                ('fwhr', models.FloatField(default=0.0)),
                ('country', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=10)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('occupation', models.TextField(null=True)),
            ],
        ),
    ]
