# Generated by Django 2.2.5 on 2019-11-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwhr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='face_coord',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='ip',
            field=models.TextField(null=True),
        ),
    ]
