# Generated by Django 2.1.1 on 2019-11-25 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fwhr', '0002_auto_20191103_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='MS_API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('smiles', models.FloatField(default=0.0)),
                ('anger', models.FloatField(default=0.0)),
                ('contempt', models.FloatField(default=0.0)),
                ('disgust', models.FloatField(default=0.0)),
                ('fear', models.FloatField(default=0.0)),
                ('happiness', models.FloatField(default=0.0)),
                ('neutral', models.FloatField(default=0.0)),
                ('sadness', models.FloatField(default=0.0)),
                ('surprise', models.FloatField(default=0.0)),
                ('bald', models.FloatField(default=0.0)),
                ('moustache', models.FloatField(default=0.0)),
                ('beard', models.FloatField(default=0.0)),
                ('sideburns', models.FloatField(default=0.0)),
            ],
        ),
    ]
